In [ ]:
import torch

a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)
"""
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])
-> 각각의 차원은 같은 사이즈를 가져야함, 1차원에 데이터 4개 2차원에 1개 3차원에 2개 4차원에 3개이거나 2개이어야 함 같은 차원에 사이즈가 다른 데이터가 존재하여 요류발생
"""
 
#-> 수정 추가코드 
a11 = torch.tensor([                 
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
    [[[1, 2, 3], [4, 5, 6]]],
])


# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')  #데이터를 직접 넣어서 초기화
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False (텐서의 모든 기울기를 저장)
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

#if you have gpu device
# -> t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# -> t1_cuda = t1.cuda()

t1_cpu = t1.cpu()   #디바이스를 cpu로 만듬

print("#" * 50, 1)

# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

# A 고찰내용
1. 괄호로 나누어진 차원을 구분할 줄 알아야 함.
2. .Tensor -> 자료형이 float32 .tensor -> 자료형 int 64.

In [ ]:
import torch
import numpy as np

l1 = [1, 2, 3]  #데이터 정의
t1 = torch.Tensor(l1) #정의한 데이터로 텐서 생성

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100 #데이터를 바꾸어도 값이 변하지 않음
l2[0] = 100 
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)

l4 = np.array([1, 2, 3])    #numpy 데이터 생성
t4 = torch.Tensor(l4)       #텐서 생성 (메모리 카피)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)    #텐서 생성 (메모리 참조)

l4[0] = 100
l5[0] = 100
l6[0] = 100     #값이 변경된다.

print(t4)
print(t5)
print(t6)

# B 고찰내용
1. 텐서는 데이터를 카피하기 때문에 데이터를 재정의해도 값이 변하지 않는다.
2. 다만 numpy자료형을 활용하면 메모리 참조가 가능해 값을 변경할 수 있다.
2. 텐서는 보통 데이터를 참조하지 않고 생성하기 때문에 삭제가 중요하다.

In [ ]:
import torch

t1 = torch.ones(size=(5,))  # 모든 값을 1로 채운다
t1_like = torch.ones_like(input=t1) #input_tensor와 사이즈가 같은 텐서를 1로 채워서 반환
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # 모든 값을 0으로 채운다
t2_like = torch.zeros_like(input=t2)    #input_tenssor와 사이즈가 같은 텐서를 0으로 채워서 반환
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)    #초기화 되지 않은 데이터를 사용해 메모리 절약가능 (임의의 값이 채워짐)
t3_like = torch.empty_like(input=t3) 
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

t4 = torch.eye(n=3)    #사이즈가 n인 단위행렬로 텐서를 채움
print(t4)


# C고찰 내용 
#### (특정 차원의 텐서를 만들고 싶을 때는 명시하지 않고 만들 수 있는가?)
1. 여러 함수로 해결 가능
2. 1로 채우거나 0으로 채우거나
3. 항등행렬로 채우는 방법이 있다
4. torch.empty는 0에 가까운 임의의 값을 가진다.

In [ ]:
import torch

t1 = torch.randint(low=10, high=20, size=(1, 2))    #정수데이터를 랜덤하게 저장 최저값, 최대값, 차원크기
print(t1)

t2 = torch.rand(size=(1, 3))    #0~1 사이에서 랜덤하게 저장
print(t2)

t3 = torch.randn(size=(1, 3))   #숫자가 등장할 확률이 정규분포를 따르는 난수를 생성한다 (평균이 0이고 표준편차가 1)
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) #숫자가 등장할 확률이 평균이 10이고 표준편차가 1인 정규분포를 따르는 난수를 생성
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)    #start ~ end사이이 값을 3등분하여 데이터를 저장한다 (1차원만 반환)
print(t5)

t6 = torch.arange(5)    #스타트 = 0 부터 1씩 끊어서 5까지 저장함 (끊는 단위를 정할 수 도 있음)
print(t6)

print("#" * 30)

torch.manual_seed(1729)     
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)  #다시 실행해도 같은 값이 나온다
print(random2)

print()

torch.manual_seed(1729)     #네트워크 생성시 항상 다른 초기값을 주면 항상 다른 훈련과정을 거치기 때문에 이를 방지하기 위해 시드를 설정한다
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)  
print(random4)


# D 고찰내용
#### 랜덤한 값은 어떻게 넣을까?
1. rand함수로 해결 가능
2. 숫자가 등장할 확률을 다르게 할 수 도 같게 할 수도 있다.
3. 실행할 때 마다 랜덤한 값이 동일하게 나오도록 할 수 있다.

In [ ]:
import torch

a = torch.ones((2, 3))  #torch.float32 데이터 타입으로 반환
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)   #0, 1만 사용할꺼니까 데이터 타입을 int16으로 변경
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.   #broadcasting 요소에 하나씩 곱해줌
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()  #.double()로 데이터타입 설정 가능
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)  #to() 함수를 통해 텐서의 자료형을 바꿀 수 있다.
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)


# E 고찰내용
#### 타입변경은 어떻게 할까?
1. 데이터 타입은 변경이 가능하다
2. .double, to() 함수등을 적극 활용할 수 있다.

In [ ]:
import torch

t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)      #각 텐서의 행이 대응해서 더해짐
t4 = t1 + t2    #.add()와 동일한 연산
print(t3)
print(t4)

print("#" * 30)

t5 = torch.sub(t1, t2)  #빼기
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)  #곱하기
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)  #나누기
t10 = t1 / t2
print(t9)
print(t10)


# F 고찰내용
#### 텐서의 계산은 어떻게 이루어지는가
1. 계산이 각 행과 열이 일치하는 값이 대응해서 이루어짐

In [ ]:
import torch

t1 = torch.dot(     #내적연산
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)   #행렬곱을 함
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)  #batch 개념 등장 3차원 행렬곱
print(t7.size())


# G고찰내용
#### 진짜 행렬곱을 하고 싶을 때는 어떻게 할까?
1. dot() 함수로 내적 연산이 가능하다.
2. mm() 함수로 행렬곱 연산이 가능하다.
3. bmm() 함수로 3차원 텐서의 연산도 가능하다.

In [ ]:
import torch

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])    #matmul() 상황에 따라 다른 매직 메서드

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])   #곱셈이 가능하도록 차원사이즈를 맞추어준다

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


# H 고찰내용
1. broadcasting란? : 차원을 맞춰주는 것 (작은 텐서를 큰 텐서에 맞추어준다)
2. matmul() 함수를 잘 사용하면 여러 텐서들을 효율적으로 계산할 수 있다.

In [ ]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)  #작은 텐서를 가상으로 큰 텐서에 맞추어 값을 만든 다음 연산한다.

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):   # 0~255 사이의 수가 0~1 사이로 바뀐다
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

# 작은 쪽에 텐서를 늘려주게 됨
# 작은 사이즈를 맞추는건 행과 열을 각자 비교한다. 

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 2차원과 3차원은 일치하지만 1차원이 없으므로 브로드캐스팅하여 차원 개수를 맞춘다
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # t13의 두 번째 차원이 일치, 세 번째 차원이 1이므로 브로드캐스팅 발생 1차원이 없으므로 브로드캐스팅 발생
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)   # 2차원이 1이므로 브로드캐스팅 발생
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)     #차원의 사이즈가 다른 경우 둘 중 하나의 크기가 1이 아니라면 에러!
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])
    
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp) #제곱함수
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


# I 고찰내용
#### 브로드캐스팅 동작에 대해
1. 차원의 개수가 다르면 브로드캐스팅이 일어난다.
* 작은 텐서의 앞쪽에 차원이 추가되며 해당 차원의 크기는 1이다.
2. 어떤 차원의 크기가 1이면 브로드캐스팅이 일어난다.
* 차원의 개수가 같지만 한 차원의 크기가 1인 경우, 다른 텐서에 맞추어 확장된다. 
3. 브로드캐스팅은 뒤 차원부터 이루어진다.

In [ ]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])    #2차원의 주소가 1인 모든 데이터를 출력
print(x[1, 2])  # >>> tensor(7) #주소가 1,2,인 데이터 출력
print(x[:, -1])  # >>> tensor([4, 9, 14)    #2차원의주소가 가장 큰 데이터를 모두 출력

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])    #교집합을 생각하면 쉽다.

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1   #열차원으로 1,2,3 행차원으로 2인 주소만 1로 값을 변경
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


# J 고찰내용
#### 텐서의 인덱싱과 슬라이싱에 대해
1. 교집합을 생각하면 쉽게 파악 가능하다


In [ ]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])   # 2,3 
t2 = t1.view(3, 2)  # Shape becomes (3, 2)  # 3,2으로 변경
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)   # 1,6으로 변경
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4) #멀티 차원으로 만드는게 가능
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])    

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,) # 사이즈가 1인 모든 차원을 제거

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)  # 1차원이 사라지고 3,1이 남음
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)  #뒤 차원에 사이즈가 1인 차원이 추가 됨 
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)   #(2,3)인 텐서에 2차원에 사이즈가 1인 차원을 추가함
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)   #다차원을 1차원으로 바꿈

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)   #start_dim을 해주면 1 주소부터 합치기 때문에 0 주소는 살아있는다.

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])   각 차원을 몇 차원으로 바꿀건지를 명시

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still 
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)    #행과 열 교환

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


# K 고찰내용
#### 텐서의 차원과 크기가 다른경우 바꾸어서 연산해줘야하는데 어떻게 할 수 있을까?
1. view() 함수와 reshape(input, shape) 함수를 통해 가능하다.
* 데이터는 바꾸지 않고 shape만 바꾼다.
* view()는 연속된 함수만 가능하다. (데이터를 참조하여 메모리절약)
* reshape()는 데이터를 카피가 가능해 비연속적이어도 가능하다. (연속된 값은 참조를 한다)
2. unsqueeze() 차원을 펼치다.
* 차원을 추가할 수 있다
* squeeze() 사이즈가 1인 차원을 없앤다.
3. flatten() 함수를 사용하면 다차원 텐서를 1차원으로 바꾸어준다.
4. permute() 차원개수는 유지, 사이즈를 바꾼다.

In [ ]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) # 2차원을 기준으로 텐서를 합쳐버린다. (나머지 차원의 사이즈가 같아야 가능하다)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0) 
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3]) 1차원의 사이즈가 변함
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])  # 2차원의 사이즈가 변함
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3]) # 1차원만 사이즈가 변함
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])  # 3차원의 사이즈만 변함
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


# I 고찰내용
#### 쌓는 방법
1. cat()함수로 n차원을 기준으로 합쳐버린다.

In [ ]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)   #1차원을 새로 생성 (t4의 연산과 같다)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0) #차원이 하나 더 늘어난다.
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

# M 고찰내용
#### 새로운 차원으로 확장하여 텐서를 병합한다.
1. stack() 없는 차원을 확장 한 후 병합한다.
* cat()는 차원은 변하지 않지만 stack()는 차원이 변한다.


In [ ]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))  #수평으로 병합한다.
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


# N 고찰내용
1. vstack() 수직으로 쌓는다.
2. hstack() 수평으로 쌓는다.
3. 차원이 변하진 않는다.
4. 차원의 개수가 변하지 않는걸 유의하자.